version: "3.9"

services:
  ##############################
  # Backend Container
  ##############################
  postgres:
    container_name: handshake_postgres
    image: postgres:10.7
    restart: always
    volumes:
      - ./server/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5445:5432'


  pgadmin:
    container_name: handshake_pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: service_started


  api:
    env_file: "./server/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: api
    restart: "no"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "julianrajman/handshake:backend"
    depends_on:
      postgres:
        condition: service_started

    ports:
      - "3000:3000"

  #############################
  # Frontend Container
  #############################
  ui:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "julianrajman/handshake:frontend"
    restart: always
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

volumes:
  handshake: