version: '3'
services:
  db:
    container_name: pg_container
    image: postgres:10.7
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5445:5432'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
